### ISSUE TITLE
I don't understand what the endstop in this place does

### ISSUE THREAD

**Issue by du5778** [Annex-Engineering/Chhogori-K2-Summit-Edition#1]
![image](https://user-images.githubusercontent.com/71308261/93167722-cc4a7780-f753-11ea-9fbf-b9801f658cdd.png)

**Comment by Tuz550** [comment]
The printer has a vertically moving bed, printing at the top and moving downwards. From the picture, it looks like that is the highest extent limit switch of the Z axis.

**Comment by Annex-Engineering** [comment]
Those switches are emergency stop buttons, because the bed is on springs, if one was to ram the nozzle into the bed by accident, this will turn the machine off. They are entirely optional.
