### ISSUE TITLE
What does this assembly do？I have been studying recently K2,it's very good  and I am going to do this, is there an installation tutorial？

### ISSUE THREAD

**Issue by du5778** [Annex-Engineering/Chhogori-K2-Summit-Edition#2]
![image](https://user-images.githubusercontent.com/71308261/93416890-507a3780-f8d9-11ea-82dc-1b721960e9ac.png)

**Comment by Annex-Engineering** [comment]
It's a cable anchor for the umbilical to the tool head. We don't use cable chains as they add unnecessary stress on the cables.
