### ISSUE TITLE
Back right X stepper collides with right cable pass-through on the 2.2 frame setup

### ISSUE THREAD

**Issue by wlhlm** [Annex-Engineering/Chhogori-K2-Summit-Edition#5]
Seems like back right stepper on the gantry obstructs the cable hole on the new 2040 frame:
![Screenshot-2022-03-07-172703](https://user-images.githubusercontent.com/1928113/157089596-77ce4da5-e567-451f-a6ca-54bf9e285b5f.png)

**Comment by Trails5000** [comment]
fixed with commit: https://github.com/Annex-Engineering/Chhogori-K2/commit/2baa07d4b91d5fae562b1b8711de88642b03c4b1
